### ISSUE TITLE
请问为什么CMeIE是分两阶段建模呢？

### ISSUE THREAD

**Issue by laonafahaodange** [CBLUEbenchmark/CBLUE#10]
ER模型的输出是否有输入到RE模型？

**Comment by flow3rdown** [comment]
您好，CMeIE的实现参考的Pipeline方法[https://arxiv.org/pdf/2010.12812.pdf](https://arxiv.org/pdf/2010.12812.pdf)，先进行实体词的识别，再进行实体与实体间的关系分类，所以ER模型的输出是有被RE模型使用的。
