### ISSUE TITLE
请问排行榜上的CMeIE-V2 f1结果是RE任务的呢？还是端到端评测的呢？

### ISSUE THREAD

**Issue by QiQingY** [CBLUEbenchmark/CBLUE#11]

**Comment by flow3rdown** [comment]
您好，会对预测的SPO结果（包括"subject", "predicate", "object"3个字段）和测试集标注结果进行精准匹配，具体细节请参考https://tianchi.aliyun.com/dataset/95414

**Comment by QiQingY** [comment]
> 

所以就是针对一条样本，假设我预测的结果是[(s1,p1,o1), (s2,p2,o2)]，而标注结果是 [(s1,p1,o1)]，那么precision就是1/2，recall是1/1，对吗？

**Comment by flow3rdown** [comment]
对的，最终会用Micro-F1进行评估
