### ISSUE TITLE
有无针对CMedCausal数据集的任务baseline？

### ISSUE THREAD

**Issue by yfangZhang** [CBLUEbenchmark/CBLUE#12]
CHIP2022-医疗因果实体关系抽取的任务源码在哪里获取

**Comment by zxlzr** [comment]
您好，非常抱歉cblue没有包含您提到的数据集。

**Comment by chenmosha** [comment]
Hi, there:

The CMedCausal dataset is newly added to CBLUE, so the CBLUE benchmark codebase doesn't have a baseline for CMedCausal.
Maybe you can visit https://link.springer.com/book/10.1007/978-981-99-4826-0 to check if the top winners have shared their solutions.
