### ISSUE TITLE
CMelE数据英文版请问

### ISSUE THREAD

**Issue by pangpang-xuan** [CBLUEbenchmark/CBLUE#13]
您好，我想获得CMelE中relation的英文版，不知道有什么渠道，感谢

**Comment by pangpang-xuan** [comment]
![image](https://github.com/CBLUEbenchmark/CBLUE/assets/142560164/8ae8fa2d-e93c-4dd1-97ef-c4495cacbf0e)

类似上述截图中的关系对应的英文表达

**Comment by zxlzr** [comment]
您好，那个是我们写论文时候自行翻译的，您可以自行翻译

**Comment by pangpang-xuan** [comment]
> 您好，那个是我们写论文时候自行翻译的，您可以自行翻译

您的数据集是行业标杆，我还是想跟你们翻译的结果保持一致，以便复现结果。

**Comment by zxlzr** [comment]
您好，这个标签您可以参考论文里的翻译，标签英文对训模型影响不大的

**Comment by zxlzr** [comment]
对模型来说就是个id

**Comment by pangpang-xuan** [comment]
> 您好，这个标签您可以参考论文里的翻译，标签英文对训模型影响不大的

好的 我就怕翻译结果不一致，输入给模型的id出现偏差，可能导致模型的理解发生偏差，好的 感谢您 我就按照您论文的翻译examples进行翻译了。

**Comment by zxlzr** [comment]
好的有问题随时交流
