### ISSUE TITLE
 您好，可以同意下我在阿里云上面申请的数据集吗？CBLUE2.0的用于学术研究.谢谢。或者发送到我的邮箱songxian1129@163.com非常感谢

### ISSUE THREAD

**Issue by songxian1129** [CBLUEbenchmark/CBLUE#15]

**Comment by zxlzr** [comment]
您好，这里是CBLUE1的git，您需要CBLUE2请您联系天池工作人员发邮件或发信息。

**Comment by songxian1129** [comment]
你好 我需要也可以。我主要想要里面的CMEEE第一个版本。谢谢



在 2024-07-11 15:21:23，"Eric" ***@***.***> 写道：

您好，这里是CBLUE1的git，您需要CBLUE2请您联系天池工作人员发邮件或发信息。

**Comment by zxlzr** [comment]
您在天池直接提交会有人审批的

**Comment by songxian1129** [comment]
好的 谢谢。我看不在维护，我以为不能下载呢。谢谢



在 2024-07-11 15:57:22，"Eric" ***@***.***> 写道：

您在天池直接提交会有人审批的
