### ISSUE TITLE
你好 您们这个测评结果结束了吗

### ISSUE THREAD

**Issue by songxian1129** [CBLUEbenchmark/CBLUE#16]

**Comment by zxlzr** [comment]
您好，这个评测是长期的，一直可以提交

**Comment by songxian1129** [comment]
> 您好，这个评测是长期的，一直可以提交

你好，可以发个连接吗？一直没找到在哪。一般提交之后多久出结果

**Comment by songxian1129** [comment]
好的 谢谢

**Comment by songxian1129** [comment]
一般多久能出结果

**Comment by songxian1129** [comment]
你好 这个提交之后，多久会有结果。



在 2024-07-12 12:14:57，"Eric" ***@***.***> 写道：

您好，这个评测是长期的，一直可以提交

**Comment by zxlzr** [comment]
您好，评测是天池负责的，不是我们这里管的，建议您在天池平台询问

**Comment by songxian1129** [comment]
好的谢谢
.是不是CMEEE第一版的停止测评了，我只看到第2板
