### ISSUE TITLE
模型加载

### ISSUE THREAD

**Issue by Smile-L-up** [CBLUEbenchmark/CBLUE#5]
您好，我想请教一下。在模型加载时出现如下错误。我自己下载了模型文件包含google_model.bin、google_vocab.txt、google_config.json三个文件，放在了bert-base目录下仍然报错。
OSError: Can't load tokenizer for 'data/model_data/bert-base'. Make sure that:

- 'data/model_data/bert-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'data/model_data/bert-base' is the correct path to a directory containing relevant tokenizer files

**Comment by flow3rdown** [comment]
您好，我们在readme里列出了使用的所有预训练模型的链接，您可以试一下 [bert-base](https://github.com/ymcui/Chinese-BERT-wwm)
