### ISSUE TITLE
I am unable to submit through Tianchi

### ISSUE THREAD

**Issue by MattYoon** [CBLUEbenchmark/CBLUE#6]
Hi,
when I try to submit my results through this [link](https://tianchi.aliyun.com/dataset/dataDetail?dataId=95414#5),
I get a message that I first need to improve Personal Information and become LV1.

However, I cannot edit my Personal Information, as majority of the boxes are grayed out.
I have completed the authentication through Alipay, however the boxes are still grayed out.
![tianchi](https://user-images.githubusercontent.com/57797966/155264122-a34de762-ca87-4b5d-8e48-7ba640da17e6.PNG)

I have contacted Tianchi through email but I haven't heard from yet.
Meanwhile, I found this [link](https://tianchi.aliyun.com/forum/issueDetail?postId=260351) in the forum.
Is there a way that you can allow International accounts to submit even when it is LV0?
(I am currently using an international account and it still says to update my personal information to submit.)
Since I am not able to upgrade to LV1.

Thank You.

**Comment by MattYoon** [comment]
I got a response from Tianchi.
It seems due to terms in EU, International Accounts cannot update their information to the platform.
If there is no way to relax the LV1 regulation on your hand,
maybe you should consider releasing CBLUE on other platforms as well to appeal to the international audiences.

![response](https://user-images.githubusercontent.com/57797966/155268123-fc1433d8-4630-44cb-a922-dc80264db0ad.jpg)

**Comment by flow3rdown** [comment]
Hi,  sorry for bringing you inconvenience! We have contacted Tianchi about the problem with the international account. Thanks for your attention!

**Comment by chenmosha** [comment]
Hi, @MattYoon :

Thanks for your detailed tracking information, we will try to resolve the issue and come back to you asap.

Regards,
Mosha
